### ISSUE TITLE
Fix all h1 elements and center text

### ISSUE THREAD

**Issue by CherylCrawford** [TravelAmore/TravelAmore.github.io#10]
They each need to be centered over the "glass" box (transparent background) .  Put margin or padding (?) above the h1 on the Testimonial page ?

**Comment by comaldave** [comment]
- [ ] The h1 in main on the disclaimer page needs leading and trailing spaces.
This is the last thing to do on this issue.

**Comment by CherylCrawford** [comment]
completed
