### ISSUE TITLE
Things to do for Map 

### ISSUE THREAD

**Issue by CherylCrawford** [TravelAmore/TravelAmore.github.io#3]
- [x] - edit map.html, confirm that contact us in nav is spelled correctly.
- [x] - open two instances of file explorer. Point one at the root directory of the TravelAmore site. Point t 
         the other to the root directory of your homework with the military map. Copy the assets used 
         (map, pictures, icon) from the homework to TravelAmore, no need to put them in image, keep 
         them in root as they are temporary.
- [x] - open the html from the military map and find the element that contains the map, links, pictures, and articles and copy this one element and paste it into element main of map.html
- [x] - open the css from the military map and find the styling for the elements that you have just copied, copy them and paste them into the map section of your TravelAmore css file
- [x] - commit 
- [x] - The military map may now be working on map.html. If it is not working, you will need to make corrections to the css so that the styles are properly applied.
- [x] - element containing the map and articles need to be converted to a flex container. The map is a flex child assigned to the top right, the articles are flex child assigned to center left. You may have to adjust max-width of the child elements to achieve two columns.
- [x] - Now that you have a working military map, you can commit, sync, and start collecting assets such as pictures of italy, replace icon markers with hearts, you already have italy.svg.
- [x] - Replace the battle icons to heart icons
- [x] -  Replace the military map with italy.svg
- [x] - Replace articles about battlefields with articles about tourist sites.
- [x] - Replace pictures of battlefield with pictures of Italy
- [x] -  Move the location of the buttons on the map to the correct cities.
- [x] - Make any corrections need on styling the articles.
- [x] - commit and sync.

**Comment by comaldave** [comment]
Completed
