### ISSUE TITLE
Fix #navleft ul container 

### ISSUE THREAD

**Issue by CherylCrawford** [TravelAmore/TravelAmore.github.io#4]
- [x] fix width of ul container in nav#left

**Comment by comaldave** [comment]
### I added` padding: 0 0;` and `margin-left: 50px;` to nav#left.
### I added `padding: 0 0;` to nav#left to override webkit defaults.
`
    nav#left {
      flex-grow: 2;
      min-height: 90vh - 6rem;
      mask-image: linear-gradient(90deg, rgba(255, 255, 255, 0) 0%, #ffffff 25%, #ffffff 75%, rgba(255, 255, 255, 0) 100%);
      padding: 0 0;
      margin-left: 50px;
    }

nav#left ul {
  /* flex-direction: column;*/
  list-style-type: none;
  background: linear-gradient(90deg, rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.2) 25%, rgba(255, 255, 255, 0.2) 75%, rgba(255, 255, 255, 0) 100%);
  box-shadow: 0 0 25px rgba(0, 0, 0, 0.1), inset 0 0 1px rgba(255, 255, 255, 0.6);
  width: 220px;
  padding: 0 0;
}
`

**Comment by CherylCrawford** [comment]
finished
